---
- yum_repository:
    name: packages-microsoft-com-mssql-server
    description: packages-microsoft-com-mssql-server
    baseurl: https://packages.microsoft.com/rhel/7/mssql-server/
    enabled: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Install microsoft sql server
  yum: name=mssql-server

- name: Install expect
  yum: name=expect

- name: Initial setup of sql server
  shell: expect -c 'spawn /opt/mssql/lib/mssql-conf/mssql-conf.py setup; expect license; send "Yes\n"; expect password; send "{{sa_password}}\n"; expect password; send "{{sa_password}}\n"; expect completed; interact'
  ignore_errors: true
  register: res

- name: Initial setup of sql server (license already accepted)
  shell: expect -c 'spawn /opt/mssql/lib/mssql-conf/mssql-conf.py setup; expect password; send "{{sa_password}}\n"; expect password; send "{{sa_password}}\n expect completed completed"; interact'
  when: res.stdout.find('password policy requirements') != -1
  
- name: Stop sql server if it was already running and initialized
  service: name=mssql-server state=stopped
  when: res.stdout.find('SQL Server is running') != -1
    
- name: Set sql server if it was already running
  shell: expect -c 'spawn /opt/mssql/lib/mssql-conf/mssql-conf.py setup; expect password; send "{{sa_password}}\n"; expect password; send "{{sa_password}}\n"; send "start\n"; expect completed; send "end\n";  interact'
  when: res.stdout.find('SQL Server is running') != -1
  
- name: Start sql server
  service: name=mssql-server state=started enabled=yes
